# rtp2httpd default config
[global]
verbosity = 2
#listen = 0.0.0.0:5140
#maxclients = 20
maxclients = 5
xff = true
workers = 1
buffer-pool-max-size = 16384
udp-rcvbuf-size = 524288
mcast-rejoin-interval = 0
ffmpeg-args = -hwaccel+none
video-snapshot = false
status-page-path = /status
player-page-path = /player
setting-page-path = /setting
use-relative-path-in-m3u = false
external-m3u = http://10.0.0.100/iptv
external-m3u-update-interval = 7200
zerocopy-on-send = false
log-format = $client_addr+[$time_iso8601]+"$service_url"+$service_type+"$upstream_url"
app-path-prefix = /tv
web-auth-user = mytv
web-auth-password = <REDACTED>
web-auth-require-local = false
[bind]
* 5140
