# Netplan configuration for IoT VLAN 10 (end0.10)
# Enables Chainedbox dual-homed connectivity to IoT segment (NVR, cameras, smart-home)

network:
  version: 2
  vlans:
    end0.10:
      renderer: NetworkManager
      dhcp4: true
      dhcp6: true
      id: 10
      link: "end0"
      networkmanager:
        name: "vlan10"
        passthrough:
          ethernet._: ""
          vlan.flags: "1"
          ipv6.addr-gen-mode: "default"
          ipv6.ip6-privacy: "-1"
          proxy._: ""
